### ISSUE TITLE
Opening inventory after being brought back to jail crashes game

### ISSUE THREAD

**Issue by jmdejong** [akulakov/little_adventure#2]
In the second room I got arrested by grobo clones and brought back to jail.
If I then try to open the inventory the game crashes

    Traceback (most recent call last):
    File "./adv.py", line 3275, in <module>
        wrapper(main, load_game)
    File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
        return func(stdscr, *args, **kwds)
    File "./adv.py", line 2896, in main
        rv = handle_ui(B, player)
    File "./adv.py", line 3025, in handle_ui
        B.display(txt)
    File "./adv.py", line 1110, in display
        w = max(len(l) for l in txt) + 1
    ValueError: max() arg is an empty sequence

**Comment by akulakov** [comment]
Thanks for reporting, pushed the fix.
